//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLocationVoiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenceRestitution
    {
        public int IdAgence { get; set; }
        public int IdVoiture { get; set; }
        public Nullable<decimal> Tarif { get; set; }
    
        public virtual Agence Agence { get; set; }
        public virtual Voiture Voiture { get; set; }
    }
}
