//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLocationVoiture.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LocationDBEntities : DbContext
    {
        public LocationDBEntities()
            : base("name=LocationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrateur> Administrateur { get; set; }
        public virtual DbSet<Agence> Agence { get; set; }
        public virtual DbSet<AgenceRestitution> AgenceRestitution { get; set; }
        public virtual DbSet<Categorie_Voiture> Categorie_Voiture { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Horaires> Horaires { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Paiement> Paiement { get; set; }
        public virtual DbSet<Parametre> Parametre { get; set; }
        public virtual DbSet<Promotion> Promotion { get; set; }
        public virtual DbSet<Statut_Location> Statut_Location { get; set; }
        public virtual DbSet<Voiture> Voiture { get; set; }
        public virtual DbSet<Tarif> Tarif { get; set; }
        public virtual DbSet<Assurance> Assurance { get; set; }
    }
}
