//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLocationVoiture.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiement
    {
        public int IdPaiement { get; set; }
        public int IdLocation { get; set; }
        public string NumeroCarte { get; set; }
        public System.DateTime DateExpiration { get; set; }
        public string CodeVerification { get; set; }
        public Nullable<System.DateTime> DatePaiement { get; set; }
        public string StatutPaiement { get; set; }
    
        public virtual Location Location { get; set; }
    }
}
